name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> 782da1dbd6b37512d7e1fefca8abbe8a3c315aaf
  - python=3.9
  - geopandas
  - cartopy
  - notebook
  - rasterio
<<<<<<< HEAD
  - pyepsg
=======
  - python
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
>>>>>>> week3
=======
  - pyepsg
>>>>>>> 782da1dbd6b37512d7e1fefca8abbe8a3c315aaf
