name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> 782da1dbd6b37512d7e1fefca8abbe8a3c315aaf
  - python=3.9
=======
  - python
>>>>>>> 77889b3f4ee7b99fda47833be92bfbaa48d4dab3
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
<<<<<<< HEAD
<<<<<<< HEAD
  - pyepsg
=======
  - python
=======
  - python=3.9
>>>>>>> c9adf11734ae0700f7f508b80f6f3cedbece8c6f
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
>>>>>>> week3
=======
  - pyepsg
>>>>>>> 782da1dbd6b37512d7e1fefca8abbe8a3c315aaf
=======
  - pyepsg
  -folium
>>>>>>> 77889b3f4ee7b99fda47833be92bfbaa48d4dab3
